#!/usr/bin/python
TOKEN = 'XXXXXXXXXXXXXxxxxxxxxxxXXXXXXXXXXXX' #YOUR DISCORD APP TOKEN CounterCord
DOGETOKEN = 'XXXXXXXXXXXXXxxxxxxxxxxXXXXXXXXXXXX' #DogeCord
TestTOKEN = 'XXXXXXXXXXXXXxxxxxxxxxxXXXXXXXXXXXX' #appTest
